### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by ikke09** [ikke09/odenwald-garbage#12]
As a user I want to have the app in a dark theme

**Comment by ikke09** [comment]
## ToDo's

- [ ] Enable Styling with a theme
-> [Theme provider](https://material-ui.com/customization/theming/)
- [ ] Build current styling as a ligth theme
- [ ] Create dark theme
- [ ] Show toggle in app to switch themes
- [ ] Save choosen theme in local storage
